project:
  type: website

website:
  title: "IWCPS Protocols"
  sidebar:
      style: "docked"
      contents:
        - text: "Welcome"
          href: index.qmd
        - section: "NWFSC Specifics"
          href: nwfsc-specifics/index.qmd
          contents:
            - nwfsc-specifics/nwfsc-datamanagement.qmd
        - section: "SWFSC Specifics"
          href: swfsc-specifics/index.qmd
          #contents:
  page-footer:
    left: "© 2026 IWCPS Team"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    number-section: false
