project:
  type: website

website:
  title: "IWCPS Protocols"
  sidebar:
      style: "docked"
      contents:
        - section: "Data Management"
          contents:
            - nwfsc-datamanagement.qmd

format:
  html:
    theme: cosmo
    toc: true