project:
  type: website

website:
  title: "IWCPS Protocols"
  sidebar:
      style: "docked"
      contents:
        - text: "Welcome"
          href: index.qmd
        - section: "Back deck basics"
          href: backdeck/index.qmd
          contents:
            - backdeck/clamssetup.qmd
            - backdeck/settingup.qmd
        - section: "NWFSC Specifics"
          href: nwfsc-specifics/index.qmd
          contents:
            - nwfsc-specifics/nwfsc-datamanagement.qmd
            - section: "FEAT Field Guide"
              href: field-guide/index.qmd
              contents:
                - fieldguide/introductions.qmd
            - section: "CLAMS Basics"
              href: clamshowto/index.qmd
              contents:
                - clamshowto/logging_events.qmd
                - clamshowto/entering_catch.qmd
                - clamshowto/finishing_tow.qmd
                - clamshowto/running_reports.qmd
        - section: "SWFSC Specifics"
          href: swfsc-specifics/index.qmd
          #contents:
  page-footer:
    left: "© 2026 IWCPS Team"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    number-section: false
