---
layout: default
title: Data Management
---

This will have introduction information about the page and the data management steps

## Data flow diagram

## Before the survey
### Steps
**Getting the CLAMS database ready**

**Deploying CLAMS database**



## During the survey
### Steps
**Data Collection**

**Backing up and creating reports**

**Initial QAQC of raw data**

**Using Docker for QAQC**
Using Docker is kind of having an apartment in an apartment building. The Docker image/template is built and users are
able to use a container to work in. So the image is like the building and the container is like an apartment in the building.
Users share the kernel (likened to plumbing in the example), but they have their own way to get in. The important thing to
remember is that **any changes made in a container are temporary**.

## After the survey
### Steps
* Additions to the data (ages, diets, etc)
* Final QAQC
* Archive staging to sqlite file and store
* Copy staging to production
* Clear out staging
