---
layout: default
title: Responsibilities and Expectations
---

Overall
You represent NOAA both on the ship and in port
o	Regardless of whether you are a NOAA employee, contractor, or volunteer, you should conduct yourself appropriately
You are responsible for yourself
o	While teamwork is key to a successful survey, the most effective teams are built on trust and accountability. Be accountable for your actions, both while on shift and off. Obey the standing orders of the ship and be courteous to your fellow shipmates.
Be available and ready for all duties
o	Because of the adaptive nature of the survey, time in between wet lab duties can vary. Work with lab leads and/or the acoustics lab to stay in touch during these times so you can be available at a moment’s notice for either a tow or other relevant duties.
o	The lab lead(s) must remain in contact with the acoustics lab while on shift. Let them know where you will be and carry a radio if necessary.
Work together to complete cruise objectives
o	In order to accomplish the varied tasks on the survey, everyone must work together. There can also be a lot of downtime so sharing the duties outside of the lab can help to keep busy.
Follow established sampling protocols
o	It is important to follow the established sampling protocols to ensure continuity between shifts, legs, and cruises. The lab lead(s) will provide a walkthrough and review of protocols at the start of each leg. Don’t hesitate to ask questions; it benefits the whole team when everyone is on the same page.
Be diligent to collect the best quality data
o	It is easy to become distracted when doing repetitive tasks. Changing jobs frequently and moving around to different stations can help.
o	Always check to make sure a species is not on the Special Sampling list before tossing. These change from cruise to cruise so please be familiar with lab document locations. Special Sampling lists will be available near the main computer in the wet lab. The lab lead(s) also have access to these species in CLAMS.
Maintain supplies and equipment
o	Keep equipment clean and in working order. Let the wet lab lead know if you notice any supplies getting low.

Duty Priorities
Collecting catch and sample data
o	While there may be other duties to work on throughout the cruise, the first priority is collecting the catch and sample data. If other duties require attention while sorting and processing is still going on in the lab, work with the acousticians who can either take care of the project or they can take someone’s place in the wet lab.
o	Note that during towing operations, NO DUMPING is allowed to minimize the possibility of recapture. As soon as the net is in the water, all dumping must cease. This is also the case for any stationary CTD stations, zooplankton net tows, Methot net tows, etc.
Prepare sensors, cameras, etc. to deploy on the net (also called ‘peripheral devices’ in this document)
o	It doesn’t take long to get sensors and other peripheral equipment ready to put onto the net. The survey tech will take care of the equipment maintained by the ship (such as the FS70), but the wet lab staff and volunteers should take care of getting the temperature and depth unit(s) ready for deployment, as well as any cameras or other peripheral equipment.
o	Be prepared to go out on deck by donning required personal protective equipment (PPE).
Help with Marine Mammal watches, when possible
o	Mammal watches before towing operations (and in some cases during) are required. If it isn’t interfering with catch processing, the wet lab staff and volunteers will need to help cover the watch so the fisher can focus on their duties. More often than not, the wet lab lead(s) will not be available for the start of the marine mammal watch due to the preparation of peripheral devices.
Retrieve sensors, cameras, etc. from the net
o	The survey tech will take care of retrieving the sensors maintained by the ship. Check with the lab lead(s) or chief scientist what the current protocol is for retrieving FEAT maintained equipment. If you are allowed on deck, you must go out with required PPE (hardhat, PFD - personal flotation device).
Maintain data from peripheral equipment
o	Data should be downloaded from the equipment and stored in the appropriate place as soon as possible to ensure that the equipment is in working order before sending it out again.
Keep lab clean between tows
o	Most of the time, there is another shift, another group, or another science center sharing the wet lab. A good rinse to knock down any fish goo, livers, blood, and other nasties is required after every tow. It’s easier to clean it when it’s fresh instead of waiting until it cakes on. Always clean the lab like it is the last tow of the day to ensure the other shift/group has a clean working environment.
Deep clean lab after every leg
o	After the last tow for the leg, a deep clean needs to be done to clean nooks and crannies to free any smelly debris. Simple green is provided (and the ship should have some as well) as well as scrub brushes and sponges in the cleaning bucket. More information on required areas to clean later in the document.
Deep, deep clean after cruise – See the cleaning sheet for details.

Keeping Busy Outside of Sampling Duties
The lab lead(s) may assign other sampling duties outside the wet lab as well as other duties for the current cruise. If you would like something to do, talk with either the lead(s) or the Chief Scientist.
